### ISSUE TITLE
How to use it on Windows？

### ISSUE THREAD

**Issue by sytgj7896321** [barasher/go-exiftool#35]
I have put the 'exiftool.exe' in %PATH%, but it still got 'Error when intializing: error when executing commande: exec: "exiftool": executable file not found in %PATH%'

**Comment by barasher** [comment]
go-exiftool has been developed on Linux and never tested on Windows.
The `exiftool` binary that `go-exiftool` is looking for has to be named `exiftool`, without any file extension. On Windows it is not `exiftool` but `exiftool.exe`. Here is the bug.
I'll have a look this week.

**Comment by barasher** [comment]
On v1.6.1 :
- on windows, by default, `exiftool.exe` will be looked for in $PATH
- you can specify an `exiftool` binary path using `SetExiftoolBinaryPath` functional option
