### ISSUE TITLE
Sorting of Exif parameters

### ISSUE THREAD

**Issue by daschkin** [barasher/go-exiftool#5]
Hi,

first of all, I want to thank you for making it possible to use exiftool in Go. I tryed it out, and it works well, but I have different order of parameters if I compare the order of parameters that I get from exiftool, if I executed it in the terminal. 
Do you have any idea, how I get the same order of parameters as from exiftool?  

Best regards,

Dorothea

**Comment by barasher** [comment]
Hi,
Thank you !
Unfortunately, picture metadata are stored on a `map` which is a data structure that does not guarantee constant order when iterating : [Go maps in action](https://blog.golang.org/go-maps-in-action).
So, you'll have to re-order metadata, sorry !
Best regards,
Arnaud
