### ISSUE TITLE
When should I call close?

### ISSUE THREAD

**Issue by qisenshi** [barasher/go-exiftool#63]
I want use stay_open in my program，but it's always running。

Will it cause OOM ？

**Comment by barasher** [comment]
Hi @qisenshi !

Go-exiftool already uses exiftool's `-stay_open` capability.

Go-exiftool will shut down the underlying exiftool when the `Close()` method is called. When should it be closed ? When you don't need it anymore. Go-exiftool should not bring any OOM error.

**Comment by barasher** [comment]
I 'm closing the issue, but don't hesitate to reopen it if you have any question
