### ISSUE TITLE
About stay_open using multiprocessing

### ISSUE THREAD

**Issue by jishi92** [barasher/go-exiftool#64]
If I have []byte data from internet and now I have to save it a file and then call `ExtractMetadataInfo(filename)`.
Does the `stay_open` pattern support input []byte data?
Such as 
`func ExtractMetadataInfo(data []byte)(rst FileMetadata,err error){
}`

**Comment by barasher** [comment]
Hi,

I've checked very quickly : it seems that `exiftool` only supports files as input.
`go-exiftool` might create a temporary file, copy the `[]byte` in the file and then extract metadata from the file but that could be done on the client-side.

Nevertheless, as I told, I've just checked quickly : do you know how to do it using `exiftool` directly ?

**Comment by barasher** [comment]
Since I dit not get any answer, I close the issue.

@jishi92 > if you come back, don't hesitate to re-open the issue.
